# Generated by Django 4.2.11 on 2024-04-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='title',
        ),
    ]
