# Generated by Django 4.2.11 on 2024-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideasapp', '0002_remove_feedback_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
